# 📊 Superstore Sales Analysis using SQL

## Project Overview

This project analyzes the Superstore sales dataset using SQL to explore sales performance, profitability, customer behavior, and business trends.

### Tools Used
- SQL
- SQLite
- Google Colab

# 1. Setup

In [1]:
# استيراد المكتبات
import pandas as pd
import sqlite3

In [4]:
# قراءة ملف البيانات
df = pd.read_csv("/content/Superstore_Comma.csv")

In [6]:
# إنشاء قاعدة بيانات SQLite
conn = sqlite3.connect("superstore.db")

In [7]:
# حفظ البيانات داخل جدول superstore
df.to_sql(
    "superstore",
    conn,
    if_exists="replace",
    index=False
)

9994

# 2. Data Exploration

In [8]:
# عرض أول 10 سجلات
query = """
SELECT *
FROM superstore
LIMIT 10;
"""

pd.read_sql(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164
5,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7.0,0.00,14.1694
6,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4.0,0.00,1.9656
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6.0,0.20,90.7152
8,9,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3.0,0.20,5.7825
9,10,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5.0,0.00,34.4700

In [9]:
# معرفة عدد الصفوف الموجودة في جدول superstore

query = """
SELECT COUNT(*) AS total_rows
FROM superstore;
"""

pd.read_sql(query, conn)

   total_rows
0        9994

In [10]:
# عرض أسماء الأعمدة وأنواع البيانات في جدول superstore

query = """
PRAGMA table_info(superstore);
"""

pd.read_sql(query, conn)

    cid           name     type  notnull dflt_value  pk
0     0         Row ID  INTEGER        0       None   0
1     1       Order ID     TEXT        0       None   0
2     2     Order Date     TEXT        0       None   0
3     3      Ship Date     TEXT        0       None   0
4     4      Ship Mode     TEXT        0       None   0
5     5    Customer ID     TEXT        0       None   0
6     6  Customer Name     TEXT        0       None   0
7     7        Segment     TEXT        0       None   0
8     8        Country     TEXT        0       None   0
9     9           City     TEXT        0       None   0
10   10          State     TEXT        0       None   0
11   11    Postal Code  INTEGER        0       None   0
12   12         Region     TEXT        0       None   0
13   13     Product ID     TEXT        0       None   0
14   14       Category     TEXT        0       None   0
15   15   Sub-Category     TEXT        0       None   0
16   16   Product Name     TEXT        0       None   0
17   17          Sales     REAL        0       None   0
18   18       Quantity     REAL        0       None   0
19   19       Discount     REAL        0       None   0
20   20         Profit     REAL        0       None   0

In [11]:
# حساب عدد القيم الفارغة في أهم الأعمدة

query = """
SELECT
COUNT(*) AS total_rows,

COUNT("Order ID") AS order_id,
COUNT("Customer ID") AS customer_id,
COUNT(Sales) AS sales,
COUNT(Quantity) AS quantity,
COUNT(Profit) AS profit

FROM superstore;
"""

pd.read_sql(query, conn)

   total_rows  order_id  customer_id  sales  quantity  profit
0        9994      9994         9994   9988      9988    9988

In [12]:
# عرض الصفوف التي تحتوي على قيم مفقودة

query = """
SELECT *
FROM superstore
WHERE Sales IS NULL
   OR Quantity IS NULL
   OR Profit IS NULL;
"""

pd.read_sql(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,182,CA-2014-166191,12/5/2014,12/9/2014,Second Class,DK-13150,David Kendrick,Corporate,United States,Decatur,...,62521,Central,TEC-AC-10004659,Technology,Accessories,Imation Secure+ Hardware Encrypted USB 2.0 Fla...,None,None,None,None
1,431,US-2016-123750,4/15/2016,4/21/2016,Standard Class,RB-19795,Ross Baird,Home Office,United States,Gastonia,...,28052,South,TEC-AC-10004659,Technology,Accessories,Imation Secure+ Hardware Encrypted USB 2.0 Fla...,None,None,None,None
2,432,US-2016-123750,4/15/2016,4/21/2016,Standard Class,RB-19795,Ross Baird,Home Office,United States,Gastonia,...,28052,South,TEC-AC-10004659,Technology,Accessories,Imation Secure+ Hardware Encrypted USB 2.0 Fla...,None,None,None,None
3,1407,US-2014-118486,4/6/2014,4/8/2014,First Class,SD-20485,Shirley Daniels,Home Office,United States,Philadelphia,...,19143,East,TEC-AC-10004659,Technology,Accessories,Imation Secure+ Hardware Encrypted USB 2.0 Fla...,None,None,None,None
4,1970,CA-2017-117485,9/23/2017,9/29/2017,Standard Class,BD-11320,Bill Donatelli,Consumer,United States,Tulsa,...,74133,Central,TEC-AC-10004659,Technology,Accessories,Imation Secure+ Hardware Encrypted USB 2.0 Fla...,None,None,None,None
5,1972,CA-2017-140242,5/6/2017,5/11/2017,Standard Class,ML-17755,Max Ludwig,Home Office,United States,Chicago,...,60623,Central,TEC-AC-10004659,Technology,Accessories,Imation Secure+ Hardware Encrypted USB 2.0 Fla...,None,None,None,None

In [13]:
# حذف الصفوف التي لا تحتوي على بيانات مالية
#لحفظ التغييرات conn.commit()
query = """
DELETE FROM superstore
WHERE Sales IS NULL
   OR Quantity IS NULL
   OR Profit IS NULL;
"""

conn.execute(query)
conn.commit()

print("تم حذف الصفوف التي تحتوي على قيم مفقودة.")

تم حذف الصفوف التي تحتوي على قيم مفقودة.

In [14]:
# التحقق من عدد الصفوف بعد الحذف

query = """
SELECT COUNT(*) AS total_rows
FROM superstore;
"""

pd.read_sql(query, conn)

   total_rows
0        9988

3. Sales Analysis

In [15]:
# حساب أهم مؤشرات المبيعات (KPIs)
#سمى الترميز العلمي (Scientific Notation)2.295274e+06 أي حوالي 2.3 مليون

query = """
SELECT

COUNT(DISTINCT "Order ID") AS total_orders,
SUM(Sales) AS total_sales,
SUM(Quantity) AS total_quantity,
SUM(Profit) AS total_profit

FROM superstore;
"""

pd.read_sql(query, conn)

   total_orders   total_sales  total_quantity  total_profit
0          5008  2.295274e+06         37841.0   285988.2777

In [16]:
#  بدالة ROUND  تقريب النتائج لتكون أوضح في التقرير

query = """
SELECT

COUNT(DISTINCT "Order ID") AS total_orders,

ROUND(SUM(Sales), 2) AS total_sales,

ROUND(SUM(Quantity), 0) AS total_quantity,

ROUND(SUM(Profit), 2) AS total_profit

FROM superstore;
"""

pd.read_sql(query, conn)

   total_orders  total_sales  total_quantity  total_profit
0          5008   2295273.92         37841.0     285988.28

In [17]:
# حساب إجمالي المبيعات لكل فئة من المنتجات

query = """
SELECT

Category,

ROUND(SUM(Sales), 2) AS total_sales

FROM superstore

GROUP BY Category

ORDER BY total_sales DESC;
"""

pd.read_sql(query, conn)

          Category  total_sales
0       Technology    834227.10
1        Furniture    741999.80
2  Office Supplies    719047.03

In [ ]:
# حساب إجمالي الأرباح لكل فئة من فئات المنتجات

query = """
SELECT
    Category,
    ROUND(SUM(Profit),2) AS total_profit
FROM superstore
GROUP BY Category
ORDER BY total_profit DESC;
"""

pd.read_sql(query, conn)

In [19]:
# حساب إجمالي المبيعات لكل منطقة (Region)
# لمعرفة المنطقة التي تحقق أعلى الإيرادات
query = """
SELECT
    Region,
    ROUND(SUM(Sales), 2) AS total_sales
FROM superstore
GROUP BY Region
ORDER BY total_sales DESC;
"""

pd.read_sql(query, conn)

    Region  total_sales
0     West    725457.82
1     East    678664.46
2  Central    500130.44
3    South    391021.20

In [18]:
# حساب إجمالي الأرباح لكل منطقة
# لمعرفة المنطقة الأكثر تحقيقًا للأرباح.

query = """
SELECT
    Region,
    ROUND(SUM(Profit),2) AS total_profit
FROM superstore
GROUP BY Region
ORDER BY total_profit DESC;
"""

pd.read_sql(query, conn)

    Region  total_profit
0     West     108418.45
1     East      91500.88
2    South      46618.05
3  Central      39450.90

In [21]:
# حساب إجمالي الأرباح لكل فئة فرعية من المنتجات
# لمعرفة أكثر المنتجات الفرعية تحقيقًا للأرباح.

query = """
SELECT
    "Sub-Category",
    ROUND(SUM(Profit), 2) AS total_profit
FROM superstore
GROUP BY "Sub-Category"
ORDER BY total_profit DESC;
"""

pd.read_sql(query, conn)

   Sub-Category  total_profit
0       Copiers      55617.82
1        Phones      44515.73
2   Accessories      41527.89
3         Paper      34053.57
4       Binders      30221.76
5        Chairs      26590.17
6       Storage      21278.83
7    Appliances      18138.01
8   Furnishings      13059.14
9     Envelopes       6964.18
10          Art       6527.79
11       Labels       5546.25
12     Machines       3384.76
13    Fasteners        949.52
14     Supplies      -1189.10
15    Bookcases      -3472.56
16       Tables     -17725.48

In [20]:
# حساب متوسط الخصم وإجمالي الأرباح لكل فئة من المنتجات
# لمعرفة هل الفئات ذات الخصومات الأعلى تحقق أرباحًا أقل.

query = """
SELECT

Category,

ROUND(AVG(Discount),2) AS avg_discount,

ROUND(SUM(Profit),2) AS total_profit

FROM superstore

GROUP BY Category

ORDER BY avg_discount DESC;
"""

pd.read_sql(query, conn)

          Category  avg_discount  total_profit
0        Furniture          0.17      18451.27
1  Office Supplies          0.16     122490.80
2       Technology          0.13     145046.20

In [22]:
# حساب متوسط الخصم وإجمالي الأرباح لكل فئة فرعية
# لمعرفة أي المنتجات الفرعية تحصل على أكبر خصومات
# وهل تحقق هذه المنتجات أرباحًا أم خسائر.
query = """
SELECT
    "Sub-Category",
    ROUND(AVG(Discount),2) AS avg_discount,
    ROUND(SUM(Profit),2) AS total_profit
FROM superstore
GROUP BY "Sub-Category"
ORDER BY avg_discount DESC;
"""

pd.read_sql(query, conn)

   Sub-Category  avg_discount  total_profit
0       Binders          0.37      30221.76
1      Machines          0.31       3384.76
2        Tables          0.26     -17725.48
3     Bookcases          0.21      -3472.56
4        Chairs          0.17      26590.17
5    Appliances          0.17      18138.01
6       Copiers          0.16      55617.82
7        Phones          0.15      44515.73
8   Furnishings          0.14      13059.14
9      Supplies          0.08      -1189.10
10    Fasteners          0.08        949.52
11    Envelopes          0.08       6964.18
12  Accessories          0.08      41527.89
13      Storage          0.07      21278.83
14        Paper          0.07      34053.57
15       Labels          0.07       5546.25
16          Art          0.07       6527.79

In [23]:
# إيجاد أعلى قيمة مبيعات في قاعدة البيانات.
query = """
SELECT
    MAX(Sales) AS highest_sale
FROM superstore;
"""

pd.read_sql(query, conn)

   highest_sale
0      22638.48

4. Profit Analysis

In [24]:
# عرض اكثر 5 فئات فرعية ربحا فقط

query = """
SELECT
"Sub-Category",

ROUND(SUM(Profit),2) AS total_profit
FROM superstore
GROUP BY "Sub-Category"
ORDER BY total_profit DESC
LIMIT 5;

"""

pd.read_sql(query, conn)

  Sub-Category  total_profit
0      Copiers      55617.82
1       Phones      44515.73
2  Accessories      41527.89
3        Paper      34053.57
4      Binders      30221.76

In [25]:
# عرض اق  5 فئات فرعية ربحا فقط
query = """
SELECT
"Sub-Category",
ROUND(SUM(Profit),2) AS total_profit
FROM superstore
GROUP BY "Sub-Category"
ORDER BY total_profit ASC
LIMIT 5;
"""
pd.read_sql(query, conn)

  Sub-Category  total_profit
0       Tables     -17725.48
1    Bookcases      -3472.56
2     Supplies      -1189.10
3    Fasteners        949.52
4     Machines       3384.76

# 5. Customer Analysis

In [ ]:
# عرض أفضل 10 عملاء من حيث إجمالي المبيعات.
query = """
SELECT
    "Customer Name",
    ROUND(SUM(Sales),2) AS total_sales
FROM superstore
GROUP BY "Customer Name"
ORDER BY total_sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

In [26]:
# عرض أفضل 10 عملاء من حيث إجمالي الأرباح.
# ملاحظه ارتفاع المبيعات لا يعني بالضرورة ارتفاع الأرباح

query = """
SELECT
    "Customer Name",
    ROUND(SUM(Profit),2) AS total_profit
FROM superstore
GROUP BY "Customer Name"
ORDER BY total_profit DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

          Customer Name  total_profit
0          Tamara Chand       8981.32
1          Raymond Buch       6976.10
2          Sanjit Chand       5757.41
3          Hunter Lopez       5622.43
4         Adrian Barton       5444.81
5          Tom Ashbrook       4703.79
6  Christopher Martinez       3899.89
7         Keith Dawkins       3038.63
8           Andy Reiter       2884.62
9         Daniel Raglin       2869.08

# 6.  Time Analysis

In [ ]:
# حساب إجمالي المبيعات لكل سنة.

query = """
SELECT
    SUBSTR("Order Date", -4) AS order_year,
    ROUND(SUM(Sales),2) AS total_sales
FROM superstore
GROUP BY order_year
ORDER BY order_year;
"""

pd.read_sql(query, conn)

In [27]:


# حساب إجمالي الارباح لكل سنة.



query = """

SELECT

    SUBSTR("Order Date", -4) AS order_year,

    ROUND(SUM(Profit),2) AS total_Profit

FROM superstore

GROUP BY order_year

ORDER BY order_year;

"""



pd.read_sql(query, conn)

  order_year  total_Profit
0       2014      49445.44
1       2015      61618.60
2       2016      81663.79
3       2017      93260.44

7.  Key Business Insights

In [28]:
# عرض الفئات التي تجاوزت أرباحها 100000
query = """

SELECT
    Category,
    ROUND(SUM(Profit),2) AS total_profit
FROM superstore
GROUP BY Category
HAVING SUM(Profit) > 100000
ORDER BY total_profit DESC;
 """
pd.read_sql(query, conn)

          Category  total_profit
0       Technology      145046.2
1  Office Supplies      122490.8

In [29]:
# عرض المناطق التي تجاوزت مبيعاتها 600000.

query = """
SELECT
    Region,
    ROUND(SUM(Sales),2) AS total_Sales
FROM superstore
GROUP BY Region
HAVING SUM(Sales) > 600000
ORDER BY total_Sales DESC;
"""

pd.read_sql(query, conn)

  Region  total_Sales
0   West    725457.82
1   East    678664.46

In [30]:
# عرض المناطق التي تجاوزت مبيعاتها 300000
# داخل فئة Technology فقط.

query = """
SELECT
    Region,
    ROUND(SUM(Sales),2) AS total_sales
FROM superstore

WHERE Category = 'Technology'

GROUP BY Region

HAVING SUM(Sales) > 200000
ORDER BY total_sales DESC;
"""

pd.read_sql(query, conn)

  Region  total_sales
0   East    264857.20
1   West    251991.83

تم عرض أول 10 طلبات من فئة Technology في منطقة West فقط. يوضح هذا الاستعلام كيفية استخدام AND لتطبيق أكثر من شرط في نفس الوقت، مما يساعد على تحليل بيانات جزء محدد من الأعمال.

In [31]:
# عرض طلبات فئة Technology الموجودة في منطقة West فقط
query = """
SELECT
    "Order ID",
    "Customer Name",
    Region,
    Category,
    Sales
FROM superstore

WHERE Category = 'Technology'
AND Region = 'West'

LIMIT 10;
"""

pd.read_sql(query, conn)

         Order ID       Customer Name Region    Category    Sales
0  CA-2014-115812     Brosina Hoffman   West  Technology  907.152
1  CA-2014-115812     Brosina Hoffman   West  Technology  911.424
2  CA-2014-143336  Zuschuss Donatelli   West  Technology  213.480
3  CA-2016-121755       Eric Hoffmann   West  Technology   90.570
4  CA-2015-135545        Kunst Miller   West  Technology   13.980
5  CA-2014-106376       Brendan Sweed   West  Technology  167.968
6  CA-2016-109806            Jim Sink   West  Technology   73.584
7  US-2015-156867       Lena Cacioppo   West  Technology  238.896
8  CA-2016-158834   Tamara Willingham   West  Technology  203.184
9  CA-2014-123260        Frank Merwin   West  Technology  176.800

تم عرض الطلبات الموجودة في منطقتي West أو East باستخدام OR. يوضح هذا الاستعلام كيفية دمج أكثر من شرط بحيث يكفي تحقق أحدهما لإظهار السجل.

In [32]:
# عرض الطلبات الموجودة في منطقة West أو منطقة East
query = """

SELECT
    "Order ID","Customer Name",Region,   Sales
FROM superstore
WHERE Region = 'West'
or Region = 'East'
ORDER BY Region DESC;
"""
pd.read_sql(query, conn)

            Order ID     Customer Name Region    Sales
0     CA-2016-138688   Darrin Van Huff   West   14.620
1     CA-2014-115812   Brosina Hoffman   West   48.860
2     CA-2014-115812   Brosina Hoffman   West    7.280
3     CA-2014-115812   Brosina Hoffman   West  907.152
4     CA-2014-115812   Brosina Hoffman   West   18.504
...              ...               ...    ...      ...
6045  CA-2017-153871   Richard Bierner   East  735.980
6046  CA-2017-153871   Richard Bierner   East   22.750
6047  CA-2017-163566   Ted Butterfield   East   16.520
6048  CA-2015-100251  Dianna Vittorini   East   31.500
6049  CA-2015-100251  Dianna Vittorini   East   55.600

[6050 rows x 4 columns]